apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-app-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          # Backend API route
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: task-backend
                port:
                  number: 8080
          # Frontend route
          - path: /
            pathType: Prefix
            backend:
              service:
                name: task-frontend
                port:
                  number: 80
